/**
 * TiffTileLoader.js
 *
 * Reads a tiled pyramidal TIFF (generated by rtiprep -tiff) via HTTP Range Requests.
 * No full file download needed, only the exact tile bytes are fetched.
 *
 * Channel layout expected from rtiprep:
 *  - IMAGE:    3 channels  (R, G, B)
 *  - LRGB_PTM: 9 channels  (a0,a1,a2, a3,a4,a5, R,G,B) × per pixel
 *  - RGB_PTM: 18 channels  (R a0..a5, G a0..a5, B a0..a5)
 *  - HSH_RTI: numCoeffs*3  (e.g. 4 coefficients → 12 channels: R k0..k3, G k0..k3, B k0..k3)
 */

import { fromUrl, Pool } from 'geotiff';
import * as THREE from 'three';
import type { RtiInfo, QuadtreeNode } from '../types/rti.js';

export class TiffTileLoader {
  url: string;
  tiff: Awaited<ReturnType<typeof fromUrl>> | null = null;
  images: Awaited<ReturnType<Awaited<ReturnType<typeof fromUrl>>['getImage']>>[] = [];
  info: RtiInfo | null = null;
  pool: Pool;
  rtiType = 4;
  numCoeffs = 1;
  samplesPerPixel = 1;

  constructor(url: string) {
    this.url = url;
    this.pool = new Pool();
  }

  /**
   * Open the TIFF and read metadata from all IFDs.
   * Returns an rtiInfo-compatible object.
   */
  async open() {
    this.tiff = await fromUrl(this.url);
    const imageCount = await this.tiff.getImageCount();

    this.images = [];
    for (let i = 0; i < imageCount; i++) {
      this.images.push(await this.tiff.getImage(i));
    }

    // Level 0 is the full resolution image
    const img0 = this.images[0];
    const width = img0.getWidth();
    const height = img0.getHeight();
    const samplesPerPixel = img0.getSamplesPerPixel();
    const tileWidth = img0.getTileWidth ? img0.getTileWidth() : 256;

    // Determine RTI type from channel count
    let type = 4; // IMAGE fallback
    let layerCount = 1;
    let numCoeffs = 1;

    if (samplesPerPixel === 3) {
      type = 4; // standard image
      layerCount = 1;
      numCoeffs = 1;
    } else if (samplesPerPixel === 9) {
      type = 2; // LRGB_PTM (3 layers × 3ch)
      layerCount = 3;
      numCoeffs = 3;
    } else if (samplesPerPixel === 18) {
      type = 3; // RGB_PTM
      layerCount = 6;
      numCoeffs = 6;
    } else if (samplesPerPixel % 3 === 0) {
      // HSH: numCoeffs = samplesPerPixel / 3
      numCoeffs = samplesPerPixel / 3;
      layerCount = numCoeffs;
      type = 1; // HSH_RTI
    }

    let description = img0.fileDirectory.ImageDescription || img0.fileDirectory[270];
    let bias = [];
    let scale = [];
    let weights = null;

    if (description) {
      try {
        if (typeof description === 'string') {
          description = description.replace(/\0/g, '').trim();
        }
        const meta = JSON.parse(description);
        if (meta.type === 'neural') {
          type = 5; // NEURAL
          layerCount = 1;
          numCoeffs = 1;
          weights = meta.weights;
        } else {
          bias = meta.bias || [];
          scale = meta.scale || [];
        }
      } catch (e) {
        console.warn("[TiffTileLoader] Failed to parse TIFF ImageDescription:", e);
      }
    }

    this.numCoeffs = numCoeffs;
    this.samplesPerPixel = samplesPerPixel;
    this.rtiType = type;

    this.info = {
      type,
      width,
      height,
      tileSize: tileWidth,
      layerCount,
      numCoeffs,
      bias,
      scale,
      weights,
      // Flag to let viewer know this is TIFF mode (no separate tile files)
      isTiff: true,
    };

    console.log(`[TiffTileLoader] Opened ${this.url}: ${width}×${height}, ${samplesPerPixel} channels, ${imageCount} pyramid levels`);
    return this.info;
  }

  /**
   * Get the pyramid level index for a given quadtree node level.
   * Level 0 = root (lowest res), level nLevels-1 = full res.
   * TIFF IFDs: IFD 0 = full res (highest), IFD n = lowest res.
   */
  _tiffLevelForNodeLevel(nodeLevel: number, nLevels: number) {
    // Node level 0 = coarsest, node level nLevels-1 = finest
    // TIFF IFD 0 = finest, IFD nLevels-1 = coarsest
    return Math.max(0, nLevels - 1 - nodeLevel);
  }

  /**
   * Load a single tile for a given quadtree node.
   * Returns an array of THREE.DataTexture objects — one per "layer" expected by the shader.
   *
   * For HSH with numCoeffs=4: returns 4 DataTextures, each RGBA (3ch from tiff + 1 padding).
   *
   * @param {object} node - quadtree node with .level, .box
   * @param {number} nLevels - total pyramid levels
   * @param {number} tileSize - tile size in pixels (256)
   */
  async loadTileTextures(node: QuadtreeNode, nLevels: number, _tileSize: number) {
    if (!node.box) return null;
    const tiffLevel = this._tiffLevelForNodeLevel(node.level, nLevels);
    const image = this.images[Math.min(tiffLevel, this.images.length - 1)];

    const imgWidth = image.getWidth();
    const imgHeight = image.getHeight();

    // Convert normalized node box [0..1] to pixel coordinates at this level.
    // The quadtree nodes are structured on a padded maxSize square box.
    const maxDim = Math.max(imgWidth, imgHeight);
    const levelMaxSize = Math.pow(2, Math.ceil(Math.log2(maxDim)));
    const woffset = (levelMaxSize - imgWidth) / 2.0;
    const hoffset = (levelMaxSize - imgHeight) / 2.0;

    const x0 = Math.max(0, Math.floor(node.box.minX * levelMaxSize - woffset));
    const y0 = Math.max(0, Math.floor((1.0 - node.box.maxY) * levelMaxSize - hoffset)); // Y-flip: TIFF origin is top-left
    const x1 = Math.min(imgWidth, Math.ceil(node.box.maxX * levelMaxSize - woffset));
    const y1 = Math.min(imgHeight, Math.ceil((1.0 - node.box.minY) * levelMaxSize - hoffset));

    const tileW = x1 - x0;
    const tileH = y1 - y0;

    if (tileW <= 0 || tileH <= 0) return null;

    // Fetch raw interleaved uint8 data for this tile window
    // geotiff.js readRasters returns one Float32Array per sample
    const rasters = (await image.readRasters({
      window: [x0, y0, x1, y1],
      interleave: false,
      pool: this.pool,
    })) as ArrayLike<number>[];

    const sample = (channel: number, idx: number) => Number(rasters[channel][idx]);
    const numChannels = this.samplesPerPixel;
    const pixelCount = tileW * tileH;

    // Build one DataTexture per shader layer
    // The shader expects each layer as an RGB texture
    const textures: THREE.DataTexture[] = [];

    for (let layer = 0; layer < this.numCoeffs; layer++) {
      const buf = new Uint8Array(tileW * tileH * 4);

      for (let y = 0; y < tileH; y++) {
        const srcRowStart = y * tileW;
        const destRowStart = (tileH - 1 - y) * tileW;
        for (let x = 0; x < tileW; x++) {
          const srcIdx = srcRowStart + x;
          const destIdx = destRowStart + x;
          let r, g, b;

          if (this.rtiType === 5) {
            // Neural RTI: 4 latent channels
            r = sample(0, srcIdx);
            g = sample(1, srcIdx);
            b = sample(2, srcIdx);
            const a = sample(3, srcIdx);
            buf[destIdx * 4 + 0] = r;
            buf[destIdx * 4 + 1] = g;
            buf[destIdx * 4 + 2] = b;
            buf[destIdx * 4 + 3] = a;
            continue; // Skip the default packing below
          }

          if (this.rtiType === 4) {
            // Standard image — single layer
            r = sample(0, srcIdx);
            g = sample(1, srcIdx);
            b = sample(2, srcIdx);
          } else if (this.rtiType === 2) {
            // LRGB_PTM: layer 0 = channels 0,1,2 / layer 1 = 3,4,5 / layer 2 = 6,7,8
            r = sample(layer * 3 + 0, srcIdx);
            g = sample(layer * 3 + 1, srcIdx);
            b = sample(layer * 3 + 2, srcIdx);
          } else if (this.rtiType === 3) {
            // RGB_PTM: R coeffs 0..5, G coeffs 6..11, B coeffs 12..17
            r = sample(layer, srcIdx);
            g = sample(6 + layer, srcIdx);
            b = sample(12 + layer, srcIdx);
          } else {
            // HSH: R coeffs 0..n-1, G coeffs n..2n-1, B coeffs 2n..3n-1
            r = sample(layer, srcIdx);
            g = sample(this.numCoeffs + layer, srcIdx);
            b = sample(2 * this.numCoeffs + layer, srcIdx);
          }

          buf[destIdx * 4 + 0] = r;
          buf[destIdx * 4 + 1] = g;
          buf[destIdx * 4 + 2] = b;
          buf[destIdx * 4 + 3] = 255;
        }
      }

      const tex = new THREE.DataTexture(buf, tileW, tileH, THREE.RGBAFormat);
      tex.colorSpace = THREE.NoColorSpace;
      if (this.rtiType === 5) {
        tex.minFilter = THREE.LinearFilter;
        tex.magFilter = THREE.LinearFilter;
      }
      tex.needsUpdate = true;
      textures.push(tex);
    }

    return textures;
  }
}
