/**
 * Reads a tiled pyramidal TIFF (generated by rtiprep -tiff) via HTTP Range Requests.
 * Exact tile byte ranges — geotiff BlockedSource is disabled so parallel fetches
 * cannot be merged into huge ranges.
 *
 * Channel layout expected from rtiprep:
 *  - IMAGE:    3 channels  (R, G, B)
 *  - LRGB_PTM: 9 channels  (a0,a1,a2, a3,a4,a5, R,G,B) × per pixel
 *  - RGB_PTM: 18 channels  (R a0..a5, G a0..a5, B a0..a5)
 *  - HSH_RTI: numCoeffs*3  (e.g. 4 coefficients → 12 channels: R k0..k3, G k0..k3, B k0..k3)
 */

import { GeoTIFF, Pool } from 'geotiff';
import * as THREE from 'three';
import type { RtiInfo, QuadtreeNode } from '../types/rti.js';
import { paddedNodePixelWindow } from './tiffNodeWindow.js';
import { ExactRangeSource } from './tiffRangeSource.js';

const MAX_CONCURRENT_TILE_FETCHES = 8;
const DECODED_TILE_CACHE_LIMIT = 64;

type GeoTiffImage = Awaited<ReturnType<GeoTIFF['getImage']>>;

export class TiffTileLoader {
  url: string;
  tiff: GeoTIFF | null = null;
  images: GeoTiffImage[] = [];
  info: RtiInfo | null = null;
  pool: Pool;
  rtiType = 4;
  numCoeffs = 1;
  samplesPerPixel = 1;
  /** Power-of-two grid size (matches QuadtreeManager.maxSize). */
  gridSize = 1;
  /** IFD 0 width/height — padded canvas for new TIFFs, content size for legacy. */
  fullWidth = 1;
  fullHeight = 1;
  private activeFetches = 0;
  private waitQueue: Array<() => void> = [];
  private decodedTiles = new Map<string, Uint8Array>();
  private inflightTiles = new Map<string, Promise<Uint8Array>>();

  constructor(url: string) {
    this.url = url;
    this.pool = new Pool(4);
  }

  /**
   * Open the TIFF and read metadata from all IFDs.
   * Returns an rtiInfo-compatible object.
   */
  async open() {
    this.tiff = await GeoTIFF.fromSource(new ExactRangeSource(this.url), { cache: true });
    const imageCount = await this.tiff.getImageCount();

    this.images = [];
    for (let i = 0; i < imageCount; i++) {
      this.images.push(await this.tiff.getImage(i));
    }

    const img0 = this.images[0];
    const tiffWidth = img0.getWidth();
    const tiffHeight = img0.getHeight();
    const samplesPerPixel = img0.getSamplesPerPixel();
    const tileWidth = img0.getTileWidth ? img0.getTileWidth() : 256;

    let type = 4;
    let layerCount = 1;
    let numCoeffs = 1;

    if (samplesPerPixel === 3) {
      type = 4;
      layerCount = 1;
      numCoeffs = 1;
    } else if (samplesPerPixel === 9) {
      type = 2;
      layerCount = 3;
      numCoeffs = 3;
    } else if (samplesPerPixel === 18) {
      type = 3;
      layerCount = 6;
      numCoeffs = 6;
    } else if (samplesPerPixel % 3 === 0) {
      numCoeffs = samplesPerPixel / 3;
      layerCount = numCoeffs;
      type = 1;
    }

    let description = img0.fileDirectory.ImageDescription || img0.fileDirectory[270];
    let bias = [];
    let scale = [];
    let weights = null;
    let colorGain = null;
    let contentWidth = tiffWidth;
    let contentHeight = tiffHeight;

    if (description) {
      try {
        if (typeof description === 'string') {
          description = description.replace(/\0/g, '').trim();
        }
        const meta = JSON.parse(description);
        if (meta.type === 'neural') {
          if (meta.weights) {
            type = 5;
            layerCount = 1;
            numCoeffs = 1;
            weights = meta.weights;
          } else {
            console.warn('[TiffTileLoader] Neural RTI metadata is missing weights; using image shader');
            type = 4;
            layerCount = 1;
            numCoeffs = 1;
          }
        } else {
          bias = meta.bias || [];
          scale = meta.scale || [];
        }
        if (meta.colorGain && typeof meta.colorGain === 'object') {
          const r = Number(meta.colorGain.r);
          const g = Number(meta.colorGain.g);
          const b = Number(meta.colorGain.b);
          if ([r, g, b].every((n) => Number.isFinite(n))) {
            colorGain = { r, g, b };
          }
        }
        const cw = Number(meta.contentWidth);
        const ch = Number(meta.contentHeight);
        if (Number.isFinite(cw) && cw > 0) contentWidth = cw;
        if (Number.isFinite(ch) && ch > 0) contentHeight = ch;
        const gs = Number(meta.gridSize);
        if (Number.isFinite(gs) && gs > 0) {
          this.gridSize = gs;
        }
      } catch (e) {
        console.warn("[TiffTileLoader] Failed to parse TIFF ImageDescription:", e);
      }
    }

    this.numCoeffs = numCoeffs;
    this.samplesPerPixel = samplesPerPixel;
    this.rtiType = type;
    this.fullWidth = tiffWidth;
    this.fullHeight = tiffHeight;
    if (this.gridSize <= 1) {
      this.gridSize = 2 ** Math.ceil(Math.log2(Math.max(contentWidth, contentHeight)));
    }

    this.info = {
      type,
      width: contentWidth,
      height: contentHeight,
      tileSize: tileWidth,
      layerCount,
      numCoeffs,
      bias,
      scale,
      weights,
      ...(colorGain ? { colorGain } : {}),
      isTiff: true,
    };

    console.log(
      `[TiffTileLoader] Opened ${this.url}: content ${contentWidth}×${contentHeight}, TIFF ${tiffWidth}×${tiffHeight}, ${samplesPerPixel} channels, ${imageCount} pyramid levels`,
    );
    return this.info;
  }

  /**
   * Get the pyramid level index for a given quadtree node level.
   * Level 0 = root (lowest res), level nLevels-1 = full res.
   * TIFF IFDs: IFD 0 = full res (highest), IFD n = lowest res.
   */
  _tiffLevelForNodeLevel(nodeLevel: number, nLevels: number) {
    const ifdCount = this.images.length;
    if (ifdCount <= 1 || nLevels <= 1) return 0;
    const finest = nLevels - 1;
    const t = nodeLevel / finest;
    return Math.max(0, Math.min(ifdCount - 1, Math.round((1 - t) * (ifdCount - 1))));
  }

  /**
   * Map a quadtree node box to pixel coordinates at a given TIFF IFD index.
   * Always uses the same power-of-two grid as QuadtreeManager, then scales to IFD size.
   */
  _windowForNode(node: QuadtreeNode, tiffLevel: number) {
    const image = this.images[Math.min(tiffLevel, this.images.length - 1)];
    const imgWidth = image.getWidth();
    const imgHeight = image.getHeight();
    const window = paddedNodePixelWindow(
      node.box!,
      this.gridSize,
      this.fullWidth,
      this.fullHeight,
      imgWidth,
      imgHeight,
    );
    return { image, ifd: Math.min(tiffLevel, this.images.length - 1), ...window };
  }

  /**
   * Pick the coarsest IFD where the node fits in one internal TIFF tile dimension.
   */
  _selectNodeWindow(node: QuadtreeNode, nLevels: number) {
    let tiffLevel = this._tiffLevelForNodeLevel(node.level, nLevels);
    let window = this._windowForNode(node, tiffLevel);
    const internalTileSize = window.image.getTileWidth ? window.image.getTileWidth() : 256;

    while ((window.tileW > internalTileSize || window.tileH > internalTileSize) && tiffLevel < this.images.length - 1) {
      tiffLevel++;
      window = this._windowForNode(node, tiffLevel);
    }

    return window;
  }

  private async withFetchLimit<T>(task: () => Promise<T>): Promise<T> {
    while (this.activeFetches >= MAX_CONCURRENT_TILE_FETCHES) {
      await new Promise<void>((resolve) => this.waitQueue.push(resolve));
    }
    this.activeFetches++;
    try {
      return await task();
    } finally {
      this.activeFetches--;
      this.waitQueue.shift()?.();
    }
  }

  private cacheDecodedTile(key: string, bytes: Uint8Array) {
    if (this.decodedTiles.has(key)) this.decodedTiles.delete(key);
    this.decodedTiles.set(key, bytes);
    while (this.decodedTiles.size > DECODED_TILE_CACHE_LIMIT) {
      const oldest = this.decodedTiles.keys().next().value;
      if (oldest === undefined) break;
      this.decodedTiles.delete(oldest);
    }
  }

  /** Fetch one internal COG tile by grid index (exact byte range from TileOffsets). */
  async _readInternalTile(image: GeoTiffImage, ifd: number, tx: number, ty: number) {
    const key = `${ifd}:${tx}:${ty}`;
    const cached = this.decodedTiles.get(key);
    if (cached) {
      this.decodedTiles.delete(key);
      this.decodedTiles.set(key, cached);
      return cached;
    }

    const pending = this.inflightTiles.get(key);
    if (pending) return pending;

    const load = this.withFetchLimit(async () => {
      const tile = await image.getTileOrStrip(tx, ty, 0, this.pool) as
        | ArrayBuffer
        | { data: ArrayBuffer | ArrayBufferView | ArrayLike<number> };

      const raw = tile instanceof ArrayBuffer ? tile : tile.data;
      let bytes: Uint8Array;
      if (raw instanceof ArrayBuffer) bytes = new Uint8Array(raw);
      else if (ArrayBuffer.isView(raw)) bytes = new Uint8Array(raw.buffer, raw.byteOffset, raw.byteLength);
      else bytes = new Uint8Array(raw as ArrayLike<number>);
      this.cacheDecodedTile(key, bytes);
      return bytes;
    }).finally(() => {
      this.inflightTiles.delete(key);
    });

    this.inflightTiles.set(key, load);
    return load;
  }

  /**
   * Read a pixel window by fetching overlapping internal COG tiles in parallel.
   */
  async _readPixelWindow(
    image: GeoTiffImage,
    ifd: number,
    x0: number,
    y0: number,
    x1: number,
    y1: number,
  ) {
    const winW = x1 - x0;
    const winH = y1 - y0;
    const channels = this.samplesPerPixel;
    const out: Uint8Array[] = Array.from({ length: channels }, () => new Uint8Array(winW * winH));

    const tileSize = image.getTileWidth ? image.getTileWidth() : 256;
    const tx0 = Math.floor(x0 / tileSize);
    const ty0 = Math.floor(y0 / tileSize);
    const tx1 = Math.floor(Math.max(x0, x1 - 1) / tileSize);
    const ty1 = Math.floor(Math.max(y0, y1 - 1) / tileSize);

    const jobs: Array<{ tx: number; ty: number }> = [];
    for (let ty = ty0; ty <= ty1; ty++) {
      for (let tx = tx0; tx <= tx1; tx++) {
        jobs.push({ tx, ty });
      }
    }

    const tiles = await Promise.all(jobs.map(({ tx, ty }) => this._readInternalTile(image, ifd, tx, ty)));

    for (let i = 0; i < jobs.length; i++) {
      const { tx, ty } = jobs[i]!;
      const tileBytes = tiles[i]!;
      const snapX0 = tx * tileSize;
      const snapY0 = ty * tileSize;
      const overlapX0 = Math.max(x0, snapX0);
      const overlapY0 = Math.max(y0, snapY0);
      const overlapX1 = Math.min(x1, snapX0 + tileSize);
      const overlapY1 = Math.min(y1, snapY0 + tileSize);

      for (let y = overlapY0; y < overlapY1; y++) {
        const localY = y - snapY0;
        const destRow = (y - y0) * winW;
        for (let x = overlapX0; x < overlapX1; x++) {
          const localX = x - snapX0;
          const srcIdx = (localY * tileSize + localX) * channels;
          const destIdx = destRow + (x - x0);
          for (let c = 0; c < channels; c++) {
            out[c][destIdx] = tileBytes[srcIdx + c] ?? 0;
          }
        }
      }
    }

    return out;
  }

  /**
   * Load a single tile for a given quadtree node.
   * Returns an array of THREE.DataTexture objects — one per "layer" expected by the shader.
   */
  async loadTileTextures(node: QuadtreeNode, nLevels: number, _tileSize: number) {
    if (!node.box) return null;

    const { image, ifd, x0, y0, x1, y1, tileW, tileH, nx0, ny0, texW, texH } = this._selectNodeWindow(node, nLevels);

    if (tileW <= 0 || tileH <= 0) return null;

    const rasters = await this._readPixelWindow(image, ifd, x0, y0, x1, y1);

    const sample = (channel: number, idx: number) => {
      const band = rasters[channel];
      if (!band || idx < 0 || idx >= band.length) return 0;
      return band[idx]!;
    };

    const textures: THREE.DataTexture[] = [];

    for (let layer = 0; layer < this.numCoeffs; layer++) {
      const buf = new Uint8Array(texW * texH * 4);

      for (let y = 0; y < tileH; y++) {
        const srcY = y0 + y;
        const destY = texH - 1 - (srcY - ny0);
        const srcRowStart = y * tileW;
        const destRowStart = destY * texW;
        for (let x = 0; x < tileW; x++) {
          const srcIdx = srcRowStart + x;
          const destIdx = destRowStart + ((x0 + x) - nx0);
          let r, g, b;

          if (this.rtiType === 5) {
            r = sample(0, srcIdx);
            g = sample(1, srcIdx);
            b = sample(2, srcIdx);
            const a = sample(3, srcIdx);
            buf[destIdx * 4 + 0] = r;
            buf[destIdx * 4 + 1] = g;
            buf[destIdx * 4 + 2] = b;
            buf[destIdx * 4 + 3] = a;
            continue;
          }

          if (this.rtiType === 4) {
            r = sample(0, srcIdx);
            g = sample(1, srcIdx);
            b = sample(2, srcIdx);
          } else if (this.rtiType === 2) {
            r = sample(layer * 3 + 0, srcIdx);
            g = sample(layer * 3 + 1, srcIdx);
            b = sample(layer * 3 + 2, srcIdx);
          } else if (this.rtiType === 3) {
            r = sample(layer, srcIdx);
            g = sample(6 + layer, srcIdx);
            b = sample(12 + layer, srcIdx);
          } else {
            r = sample(layer, srcIdx);
            g = sample(this.numCoeffs + layer, srcIdx);
            b = sample(2 * this.numCoeffs + layer, srcIdx);
          }

          buf[destIdx * 4 + 0] = r;
          buf[destIdx * 4 + 1] = g;
          buf[destIdx * 4 + 2] = b;
          buf[destIdx * 4 + 3] = 255;
        }
      }

      const tex = new THREE.DataTexture(buf, texW, texH, THREE.RGBAFormat);
      tex.colorSpace = THREE.NoColorSpace;
      if (this.rtiType === 5) {
        tex.minFilter = THREE.LinearFilter;
        tex.magFilter = THREE.LinearFilter;
      }
      tex.needsUpdate = true;
      textures.push(tex);
    }

    return textures;
  }
}
