/**
 * TiffTileLoader.js
 *
 * Reads a tiled pyramidal TIFF (generated by rtiprep -tiff) via HTTP Range Requests.
 * No full file download needed, only the exact tile bytes are fetched.
 *
 * Channel layout expected from rtiprep:
 *  - IMAGE:    3 channels  (R, G, B)
 *  - LRGB_PTM: 9 channels  (a0,a1,a2, a3,a4,a5, R,G,B) × per pixel
 *  - RGB_PTM: 18 channels  (R a0..a5, G a0..a5, B a0..a5)
 *  - HSH_RTI: numCoeffs*3  (e.g. 4 coefficients → 12 channels: R k0..k3, G k0..k3, B k0..k3)
 */

import { fromUrl, Pool } from 'geotiff';
import * as THREE from 'three';
import type { RtiInfo, QuadtreeNode } from '../types/rti.js';

export class TiffTileLoader {
  url: string;
  tiff: Awaited<ReturnType<typeof fromUrl>> | null = null;
  images: Awaited<ReturnType<Awaited<ReturnType<typeof fromUrl>>['getImage']>>[] = [];
  info: RtiInfo | null = null;
  pool: Pool;
  rtiType = 4;
  numCoeffs = 1;
  samplesPerPixel = 1;
  /** Power-of-two grid size (matches QuadtreeManager.maxSize). */
  gridSize = 1;
  fullWidth = 1;
  fullHeight = 1;
  /** Serialize COG byte fetches so geotiff BlockedSource cannot merge parallel ranges. */
  private fetchChain: Promise<unknown> = Promise.resolve();

  constructor(url: string) {
    this.url = url;
    // Limit concurrent tile decodes to avoid flooding the server with range requests.
    this.pool = new Pool(2);
  }

  /**
   * Open the TIFF and read metadata from all IFDs.
   * Returns an rtiInfo-compatible object.
   */
  async open() {
    this.tiff = await fromUrl(this.url, { cache: true });
    const imageCount = await this.tiff.getImageCount();

    this.images = [];
    for (let i = 0; i < imageCount; i++) {
      this.images.push(await this.tiff.getImage(i));
    }

    // Level 0 is the full resolution image
    const img0 = this.images[0];
    const width = img0.getWidth();
    const height = img0.getHeight();
    const samplesPerPixel = img0.getSamplesPerPixel();
    const tileWidth = img0.getTileWidth ? img0.getTileWidth() : 256;

    // Determine RTI type from channel count
    let type = 4; // IMAGE fallback
    let layerCount = 1;
    let numCoeffs = 1;

    if (samplesPerPixel === 3) {
      type = 4; // standard image
      layerCount = 1;
      numCoeffs = 1;
    } else if (samplesPerPixel === 9) {
      type = 2; // LRGB_PTM (3 layers × 3ch)
      layerCount = 3;
      numCoeffs = 3;
    } else if (samplesPerPixel === 18) {
      type = 3; // RGB_PTM
      layerCount = 6;
      numCoeffs = 6;
    } else if (samplesPerPixel % 3 === 0) {
      // HSH: numCoeffs = samplesPerPixel / 3
      numCoeffs = samplesPerPixel / 3;
      layerCount = numCoeffs;
      type = 1; // HSH_RTI
    }

    let description = img0.fileDirectory.ImageDescription || img0.fileDirectory[270];
    let bias = [];
    let scale = [];
    let weights = null;

    if (description) {
      try {
        if (typeof description === 'string') {
          description = description.replace(/\0/g, '').trim();
        }
        const meta = JSON.parse(description);
        if (meta.type === 'neural') {
          type = 5; // NEURAL
          layerCount = 1;
          numCoeffs = 1;
          weights = meta.weights;
        } else {
          bias = meta.bias || [];
          scale = meta.scale || [];
        }
      } catch (e) {
        console.warn("[TiffTileLoader] Failed to parse TIFF ImageDescription:", e);
      }
    }

    this.numCoeffs = numCoeffs;
    this.samplesPerPixel = samplesPerPixel;
    this.rtiType = type;
    this.fullWidth = width;
    this.fullHeight = height;
    this.gridSize = 2 ** Math.ceil(Math.log2(Math.max(width, height)));

    this.info = {
      type,
      width,
      height,
      tileSize: tileWidth,
      layerCount,
      numCoeffs,
      bias,
      scale,
      weights,
      // Flag to let viewer know this is TIFF mode (no separate tile files)
      isTiff: true,
    };

    console.log(`[TiffTileLoader] Opened ${this.url}: ${width}×${height}, ${samplesPerPixel} channels, ${imageCount} pyramid levels`);
    return this.info;
  }

  /**
   * Get the pyramid level index for a given quadtree node level.
   * Level 0 = root (lowest res), level nLevels-1 = full res.
   * TIFF IFDs: IFD 0 = full res (highest), IFD n = lowest res.
   */
  _tiffLevelForNodeLevel(nodeLevel: number, nLevels: number) {
    const ifdCount = this.images.length;
    if (ifdCount <= 1 || nLevels <= 1) return 0;
    const finest = nLevels - 1;
    const t = nodeLevel / finest;
    return Math.max(0, Math.min(ifdCount - 1, Math.round((1 - t) * (ifdCount - 1))));
  }

  /**
   * Map a quadtree node box to pixel coordinates at a given TIFF IFD index.
   * Always uses the same power-of-two grid as QuadtreeManager, then scales to IFD size.
   */
  _windowForNode(node: QuadtreeNode, tiffLevel: number) {
    const image = this.images[Math.min(tiffLevel, this.images.length - 1)];
    const imgWidth = image.getWidth();
    const imgHeight = image.getHeight();

    const woffset = (this.gridSize - this.fullWidth) / 2.0;
    const hoffset = (this.gridSize - this.fullHeight) / 2.0;

    const fullX0 = node.box!.minX * this.gridSize - woffset;
    const fullY0 = (1.0 - node.box!.maxY) * this.gridSize - hoffset;
    const fullX1 = node.box!.maxX * this.gridSize - woffset;
    const fullY1 = (1.0 - node.box!.minY) * this.gridSize - hoffset;

    const scaleX = imgWidth / this.fullWidth;
    const scaleY = imgHeight / this.fullHeight;

    const x0 = Math.max(0, Math.floor(fullX0 * scaleX));
    const y0 = Math.max(0, Math.floor(fullY0 * scaleY));
    const x1 = Math.min(imgWidth, Math.ceil(fullX1 * scaleX));
    const y1 = Math.min(imgHeight, Math.ceil(fullY1 * scaleY));

    return { image, x0, y0, x1, y1, tileW: x1 - x0, tileH: y1 - y0 };
  }

  /**
   * Pick the coarsest IFD where the node fits in one internal TIFF tile dimension.
   */
  _selectNodeWindow(node: QuadtreeNode, nLevels: number) {
    let tiffLevel = this._tiffLevelForNodeLevel(node.level, nLevels);
    let { image, x0, y0, x1, y1, tileW, tileH } = this._windowForNode(node, tiffLevel);
    const internalTileSize = image.getTileWidth ? image.getTileWidth() : 256;

    while ((tileW > internalTileSize || tileH > internalTileSize) && tiffLevel < this.images.length - 1) {
      tiffLevel++;
      ({ image, x0, y0, x1, y1, tileW, tileH } = this._windowForNode(node, tiffLevel));
    }

    return { image, x0, y0, x1, y1, tileW, tileH };
  }

  /** Run COG fetches one at a time — BlockedSource batches parallel slice requests into huge ranges. */
  private runSerialized<T>(task: () => Promise<T>): Promise<T> {
    const run = this.fetchChain.then(task);
    this.fetchChain = run.catch(() => {});
    return run;
  }

  /** Fetch one internal COG tile by grid index (exact byte range from TileOffsets). */
  async _readInternalTile(
    image: TiffTileLoader['images'][number],
    tx: number,
    ty: number,
  ) {
    const tile = await this.runSerialized(() =>
      image.getTileOrStrip(tx, ty, 0, this.pool),
    ) as ArrayBuffer | { data: ArrayBuffer | ArrayBufferView | ArrayLike<number> };

    const raw = tile instanceof ArrayBuffer ? tile : tile.data;
    if (raw instanceof ArrayBuffer) return new Uint8Array(raw);
    if (ArrayBuffer.isView(raw)) {
      return new Uint8Array(raw.buffer, raw.byteOffset, raw.byteLength);
    }
    return new Uint8Array(raw as ArrayLike<number>);
  }

  /**
   * Read a pixel window by fetching each overlapping internal COG tile via
   * getTileOrStrip (one HTTP range request per compressed tile block).
   */
  async _readPixelWindow(
    image: TiffTileLoader['images'][number],
    x0: number,
    y0: number,
    x1: number,
    y1: number,
  ) {
    const winW = x1 - x0;
    const winH = y1 - y0;
    const channels = this.samplesPerPixel;
    const out: Float32Array[] = Array.from({ length: channels }, () => new Float32Array(winW * winH));

    const tileSize = image.getTileWidth ? image.getTileWidth() : 256;
    const tx0 = Math.floor(x0 / tileSize);
    const ty0 = Math.floor(y0 / tileSize);
    const tx1 = Math.floor(Math.max(x0, x1 - 1) / tileSize);
    const ty1 = Math.floor(Math.max(y0, y1 - 1) / tileSize);

    for (let ty = ty0; ty <= ty1; ty++) {
      for (let tx = tx0; tx <= tx1; tx++) {
        const tileBytes = await this._readInternalTile(image, tx, ty);
        const snapX0 = tx * tileSize;
        const snapY0 = ty * tileSize;
        const overlapX0 = Math.max(x0, snapX0);
        const overlapY0 = Math.max(y0, snapY0);
        const overlapX1 = Math.min(x1, snapX0 + tileSize);
        const overlapY1 = Math.min(y1, snapY0 + tileSize);

        for (let y = overlapY0; y < overlapY1; y++) {
          const localY = y - snapY0;
          const destRow = (y - y0) * winW;
          for (let x = overlapX0; x < overlapX1; x++) {
            const localX = x - snapX0;
            const srcIdx = (localY * tileSize + localX) * channels;
            const destIdx = destRow + (x - x0);
            for (let c = 0; c < channels; c++) {
              out[c][destIdx] = tileBytes[srcIdx + c] ?? 0;
            }
          }
        }
      }
    }

    return out;
  }

  /**
   * Load a single tile for a given quadtree node.
   * Returns an array of THREE.DataTexture objects — one per "layer" expected by the shader.
   *
   * For HSH with numCoeffs=4: returns 4 DataTextures, each RGBA (3ch from tiff + 1 padding).
   *
   * @param {object} node - quadtree node with .level, .box
   * @param {number} nLevels - total pyramid levels
   * @param {number} tileSize - tile size in pixels (256)
   */
  async loadTileTextures(node: QuadtreeNode, nLevels: number, _tileSize: number) {
    if (!node.box) return null;

    const { image, x0, y0, x1, y1, tileW, tileH } = this._selectNodeWindow(node, nLevels);

    if (tileW <= 0 || tileH <= 0) return null;

    const rasters = await this._readPixelWindow(image, x0, y0, x1, y1);

    const sample = (channel: number, idx: number) => {
      const band = rasters[channel];
      if (!band || idx < 0 || idx >= band.length) return 0;
      return Math.min(255, Math.max(0, Math.round(Number(band[idx]))));
    };

    // Build one DataTexture per shader layer
    // The shader expects each layer as an RGB texture
    const textures: THREE.DataTexture[] = [];

    for (let layer = 0; layer < this.numCoeffs; layer++) {
      const buf = new Uint8Array(tileW * tileH * 4);

      for (let y = 0; y < tileH; y++) {
        const srcRowStart = y * tileW;
        const destRowStart = (tileH - 1 - y) * tileW;
        for (let x = 0; x < tileW; x++) {
          const srcIdx = srcRowStart + x;
          const destIdx = destRowStart + x;
          let r, g, b;

          if (this.rtiType === 5) {
            // Neural RTI: 4 latent channels
            r = sample(0, srcIdx);
            g = sample(1, srcIdx);
            b = sample(2, srcIdx);
            const a = sample(3, srcIdx);
            buf[destIdx * 4 + 0] = r;
            buf[destIdx * 4 + 1] = g;
            buf[destIdx * 4 + 2] = b;
            buf[destIdx * 4 + 3] = a;
            continue; // Skip the default packing below
          }

          if (this.rtiType === 4) {
            // Standard image — single layer
            r = sample(0, srcIdx);
            g = sample(1, srcIdx);
            b = sample(2, srcIdx);
          } else if (this.rtiType === 2) {
            // LRGB_PTM: layer 0 = channels 0,1,2 / layer 1 = 3,4,5 / layer 2 = 6,7,8
            r = sample(layer * 3 + 0, srcIdx);
            g = sample(layer * 3 + 1, srcIdx);
            b = sample(layer * 3 + 2, srcIdx);
          } else if (this.rtiType === 3) {
            // RGB_PTM: R coeffs 0..5, G coeffs 6..11, B coeffs 12..17
            r = sample(layer, srcIdx);
            g = sample(6 + layer, srcIdx);
            b = sample(12 + layer, srcIdx);
          } else {
            // HSH: R coeffs 0..n-1, G coeffs n..2n-1, B coeffs 2n..3n-1
            r = sample(layer, srcIdx);
            g = sample(this.numCoeffs + layer, srcIdx);
            b = sample(2 * this.numCoeffs + layer, srcIdx);
          }

          buf[destIdx * 4 + 0] = r;
          buf[destIdx * 4 + 1] = g;
          buf[destIdx * 4 + 2] = b;
          buf[destIdx * 4 + 3] = 255;
        }
      }

      const tex = new THREE.DataTexture(buf, tileW, tileH, THREE.RGBAFormat);
      tex.colorSpace = THREE.NoColorSpace;
      if (this.rtiType === 5) {
        tex.minFilter = THREE.LinearFilter;
        tex.magFilter = THREE.LinearFilter;
      }
      tex.needsUpdate = true;
      textures.push(tex);
    }

    return textures;
  }
}
